version: "3.7"
services:
  redis-init:
    image: local/redis-swarm
    environment:
      REDIS_ROLE: init
      NUM_OF_REPLICAS: 3
      NUM_OF_SENTINELS: 3
    networks:
      - net-redis
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  redis:
    image: local/redis-swarm
    environment:
      REDIS_ROLE: replica
    networks:
      - net-redis
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  redis-sentinel:
    image: local/redis-swarm
    environment:
      REDIS_ROLE: sentinel
    networks:
      - net-redis
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  # debug:
  #   image: local/redis-swarm
  #   environment:
  #     REDIS_ROLE: debug
  #   networks:
  #     - net-redis
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     endpoint_mode: dnsrr

networks:
  net-redis:
    external: true
