---
kind: pipeline
name: redis-swarm

- name: publish
  image: plugins/docker:linux-amd64
  user: root
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    repo: cekrdoso/redis-swarm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag